#!/usr/bin/env bash

{
    cat <<EOF
// Code generated by resources/scripts/generate.sh. DO NOT EDIT.
// source: resources/web/style.css

package grpcuiredoc

const cssContent = \`
$(cd "resources/web" || true; npx postcss "*.css" --use autoprefixer | grep -v sourceMappingURL)
\`
EOF
} > "$1"

echo "OK"
