---
name: lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: nhatthm/gh-actions/checkout@master

      - name: Setup
        uses: nhatthm/gh-actions/find-go-version@master

      - name: Install Go
        uses: nhatthm/gh-actions/setup-go@master
        with:
          go-version: ${{ env.GO_LATEST_VERSION }}

      - name: Lint (Go)
        uses: nhatthm/gh-actions/golangci-lint@master


      - name: Lint (CSS)
        uses: nhatthm/gh-actions/css-lint@master
        env:
          CONFIG_PATH: "resources/web/.stylelintrc.json"
          PATTERN: "resources/web/*.css"
